import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuery } from "@tanstack/react-query";
import { createIssueTree } from "@/lib/createIssueTree";
import { IssueTree } from "@/components/issue-tree";

const inter = Inter({ subsets: ["latin"] });

const getIssues = async () => {
  const issues = await fetch("/api/hello").then((res) => res.json());
  return issues as IssueWithRelations[];
};

export default function Home() {
  const { data } = useQuery({
    queryKey: ["issues"],
    queryFn: getIssues,
  });

  const tree = createIssueTree(data ?? []);
  console.log(tree);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <IssueTree data={tree} />
      </main>
    </>
  );
}
